import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils"

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "DashBoard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={
          cn("min-h-screen bg-background font-sans antialiased", inter.className
        )}
      >
        {children}
      </body>
    </html>
  );
}
