version: '3.8'
services:

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"

  database:
    image: postgres
    container_name: order-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ordersdb
    ports:
      - "5432:5432"
